#!/bin/bash

profname="/`pwd | tail -c +2`/runbot"
profnamedot="`pwd | sed 's,/,.,g' | tail -c +2`.runbot"

sed "s,HAIBOTPATH,$profname,g" haibot.apparmor | sudo tee /etc/apparmor.d/$profnamedot
sudo aa-enforce $profname
